### ISSUE TITLE
Put time tracking/invoicing/payment info up front in its own section

### ISSUE THREAD

**Issue by cjaszewski** [ten7/contractor.ten7.com#2]
Contractors want/need to know about how to time track, submit timesheets and/or invoice so they can get paid, and this should be up front. Also it's important to spell out that they need to submit a timesheet AND an invoice in order to get paid. Some places you only need to submit a timesheet.

Suggest a structure like this for time tracking/payment
### Time Tracking and Payment Questions

- **Where do I track my time?** 
We use the Harvest app to track all time. Please track your time in real time, as you’re working on projects. Harvest has both desktop and mobile apps, and timers can also be started from tickets in Jira (for devs) as well as tasks in Asana (non-devs). 

- **How do I know which projects or tasks I should track time to?**
Your team lead will let you know which projects, tasks or categories you should be tracking time to. If you have questions about logging your time, ask Dani!

- **How often do I submit my timesheet?** 
Submit your timesheet at the end of each week. We can’t pay you unless you do. 

- **How often should I invoice?**
In addition to submitting your timesheet each week, we also need you to send us an invoice. You can do it in whatever cadence works best for you: semi-monthly, bi-weekly, weekly…just invoice us. We ask that you invoice us at least monthly.

**- Where should I send my invoice?**
Email your invoice to billing@ten7.com.

- **When/how do I get paid?**
Payment is made via direct deposit through Gusto, and you’ll typically see that money in your bank account within five business days from when you invoice.

**Comment by ivanstegic** [comment]
Thanks for the suggestions, @cjaszewski -- we'll make the enhancements.

**Comment by ivanstegic** [comment]
This was implemented https://github.com/ten7/contractor.ten7.com/commit/36a9532786a035ff086e3939bf0c7e99c5970832
