### ISSUE TITLE
Fixes for version 2.1.0

### ISSUE THREAD

**Issue by ivanstegic** [ten7/contractor.ten7.com#33]
There are some changes that need to be made for the next minor version of the site:
### 1
the `<title>` tag on the index page should not have a repeated title, i.e. it should say "TEN7 Contractor’s Quick Start" and not "TEN7 Contractor’s Quick Start - Contractor’s Quick Start" as it currently does

### 2
currently, the home page is excluded from the progress bar at the bottom of the page. We've intentionally made it a special page. This was a mistake on my part. I'd like to change this so that the index page is counted as the first page, and that the progress bar has n+1 sections as @joshcesana had originally built this. When you land on the home page there will be a progress bar in purple that is 1 of n+1 of the way complete. 

### 3
 "Let's Dive In:" card on the Index page should not have "Welcome" hard coded -- it should have the title of page no. 1. In this case, it would be "Admin"

### 4
Reduce size of logo on mobile and make sure that the Title of the site is always displayed:

<img width="612" alt="mobile header" src="https://user-images.githubusercontent.com/509217/140625671-eee3e31a-df00-4e2c-88d3-9e5dac1bf4a2.png">

### 5
Remove hover state on Hamburger and X on mobile nav

![CleanShot 2021-11-06 at 17 33 01@2x](https://user-images.githubusercontent.com/509217/140625662-76c80ad6-9bf0-4d44-803b-21684e590962.png)

### 6
Remove nav title between header and nav items and move the items up

![CleanShot 2021-11-06 at 17 35 35@2x](https://user-images.githubusercontent.com/509217/140625705-f4406878-94f0-4749-9278-759792373624.png)

### 7
Make sure that the navigation overlay does not change the height of the nav itself. It looks like a little jump when you see the video

![CleanShot 2021-11-06 at 17 40 18](https://user-images.githubusercontent.com/509217/140625806-3eb9f7e6-f260-4ca3-82f3-ad2c3f1f789f.gif)

### 8
Increase the width of the cards in the footer to aprrox 40% the width, it looks like they are around 30% right now. We might bump this up to 45%, but let's try 40% first. On mobile, they remain at 50%. Also, make sure that there is **always** padding around the arrows, especially if words get long in the NEXT card. Make sure that the text is always aligned left with the same padding on the BACK: card

![CleanShot 2021-11-06 at 17 44 39@2x](https://user-images.githubusercontent.com/509217/140626025-763ce8bd-060c-4739-bdaf-d4be5074971c.png)
s. 

### 9
Width of body text container should remain fixed and not shrink in width as the browser width approaches the container fixed width and mobile implementation. Also, the logo jumps out to the left and isn't aligned at certain widths, see here: https://cln.sh/uXn0KR

(edit)

### 10
The navigation changes to the title of the page when you are on that page. Let's change this so that it always says "Start here"

### 11
The navigation drop down always aligns itself to the left most part of the word and sticks out of the frame of the site. That's by design. Could we have it just align on the right side of the nav word? That way, its always on the inside of the side. I think that might make the issue 9 above easier too.

![CleanShot 2021-11-06 at 18 27 20@2x](https://user-images.githubusercontent.com/509217/140626819-4ee5a901-8240-4616-9fd0-e9f16d6e8cc0.png)

**Comment by joshcesana** [comment]
https://github.com/ten7/contractor.ten7.com/pull/35

**Comment by ivanstegic** [comment]
@joshcesana just did a quick evaluation locally and all of this looks good, except that there is no BACK: card on the Admin page. I think that's by design, but let's change that. Let's add a BACK card on the Admin page, and have it include the OPENER title. So, in this case, it would read "Back:" and then "Introduction"

**Comment by ivanstegic** [comment]
Closed by https://github.com/ten7/contractor.ten7.com/pull/35
