### ISSUE TITLE
Sub footer area should be purple

### ISSUE THREAD

**Issue by ivanstegic** [ten7/contractor.ten7.com#34]
If you happen upon a page that has very little content in it, you may end up having your browser be taller than the total height of the webpage. When this happens, there is a white space at the bottom of the page -- this should just be the same purple color as the purple above it:

![CleanShot 2021-11-06 at 19 24 54@2x](https://user-images.githubusercontent.com/509217/140627795-64ed70cf-fa08-45a7-b805-5fed2a9932d0.png)

**Comment by joshcesana** [comment]
https://github.com/ten7/contractor.ten7.com/pull/35

**Comment by ivanstegic** [comment]
Closed by https://github.com/ten7/contractor.ten7.com/pull/35
