### ISSUE TITLE
Bulleted list headlines, footer hover states

### ISSUE THREAD

**Issue by ivanstegic** [ten7/contractor.ten7.com#39]
- Please bring down the weight of the bulleted list headline — right now it’s feeling a little heavy
- In the footer, I think the hover state for the links should just be an underline instead of electric purple.

<img width="941" alt="screen_shot_2021-11-08_at_10 43 14_am" src="https://user-images.githubusercontent.com/509217/140783241-8c3094a3-d73e-45ab-8c63-79d71ebfaf55.png">

**Comment by joshcesana** [comment]
https://github.com/ten7/contractor.ten7.com/pull/40
